### ISSUE TITLE
Why is v3 using Eris but also requires the NodeJS version?

### ISSUE THREAD

**Issue by NanoAi** [brussell98/BrussellBot#11]
These are questions about... https://github.com/brussell98/BrussellBot/tree/v3

Why is v3 using Eris but also requires the NodeJS version?
Is the NodeJS version v2?
Will there be a v3 for the NodeJS version?

**Comment by brussell98** [comment]
I don't understand what you are asking here.
Eris is a library for Discord using NodeJS.

**Comment by abalabahaha** [comment]
Eris is a NodeJS Discord library, not a programming language

**Comment by NanoAi** [comment]
Oh okay I was a little confused. I thought it was some new node like JS. As
allot of new ones are coming out.
