### ISSUE TITLE
Where are many of the commands?

### ISSUE THREAD

**Issue by oneechanhax** [brussell98/BrussellBot#13]
I like to host my own bots, I dont know why but I love to.
But while im using the "Bot-chan" Bot, i see that there is a new version available. As any person would do i would try to update it. I did it successfully but I noticed that it has VERY BASIC commands and nothing more. Is there supposed to be more files in the commands folder?
Well Im staying with version 2.3.1 until Mirai has the same or more functionality.

**Comment by brussell98** [comment]
I decided to separate the bot base and the bot with Mirai. The commands (except for a few) are now closed source*.

The Mirai Bot on GitHub is now intended for people wanting to write their own commands.

**Comment by nandub** [comment]
Do you have a  document that shows how to create new commands?

**Comment by brussell98** [comment]
The examples/instructions are in the README.md

**Comment by nandub** [comment]
Yes, but I was looking more for an api that explain what each of the option means, specially how the Task works.

**Comment by brussell98** [comment]
Well I believe the Readme explains what they are for/do. There is also a
link to the bot's api docs and the Eris docs.

**Comment by oneechanhax** [comment]
Is there a way to port the commands from 2.3.1 to 3.0.2?
I wouldnt mind if its not very efficient as its just on 1 server.
Am I also allowed to distribute 2.3.1 if someone else would want it?

**Comment by brussell98** [comment]
Yes the commands can be re-made. It just would need to use the new API and Eris.
As for the second question, you can still download it on GitHub, just go backwards and browse at a 2.3.1 commit.
