### ISSUE TITLE
Making a command

### ISSUE THREAD

**Issue by Fruitspunches** [brussell98/BrussellBot#16]
I've tried following the guidance that you've given on adding a command to Mirai, however every time I've tried to add a command, it does not work. This is mainly because I don't fully understand the guidance that you have provided.

Bear in mind I have 0 knowledge with Javascript.

**Comment by brussell98** [comment]
Well you should really know _at least_ basic JavaScript when trying to write a command.
If you want you can try posting your code here or on the discord server and seeing if anyone will help out.

**Comment by Fruitspunches** [comment]
Ah, alright. I thought so, thanks.
