### ISSUE TITLE
Twitch follow command stacks notifications

### ISSUE THREAD

**Issue by Newbhope** [brussell98/BrussellBot#24]
Following a twitch channel multiple times causes Mirai to create multiple messages instead of only one. Unfollowing and refollowing doesn't fix this.

![capture](https://user-images.githubusercontent.com/9125774/28643977-3f381802-721d-11e7-8b3a-c63803d3444a.PNG)

**Comment by brussell98** [comment]
Thanks for reporting the behavior that causes this. I've had reports of this for a long time now but couldn't figure out why it was actually happening. I've found the line of code that seems to be causing this and corrected it.

I've applied a hotfix to Mirai and this should be fixed on the live version.

**Comment by Newbhope** [comment]
Thanks for the fix and quick response!
