### ISSUE TITLE
Twitch following channels live notifications not working anymore

### ISSUE THREAD

**Issue by johnmcdee** [brussell98/BrussellBot#29]
Hi,

First of all thanks for your work and making the Bot :)

Noticed that the Bot stopped posting notifications that a channel is live after 11th of May. 

In the Bot Dashboard in the "Twitch Notifications" section it's showing the channel as offline, even if it's online currently.
Tried to refollow the channel but when issuing the m.twitch unfollow command the bot answers with "Error: status code 401". 

Twitch API issues?

**Comment by brussell98** [comment]
This is the repository for mirai-bot-core, not the Mirai Discord bot. All questions about the bot should go on the [official server](https://discord.gg/rkWPSdu), where you will find your answer in the announcements.
