### ISSUE TITLE
Issue with m.airing notify channel anime command

### ISSUE THREAD

**Issue by MrPakoras** [brussell98/BrussellBot#30]
_Not sure if this is the right place to ask, but didn't know anywhere else to ask._

**Issue:** When you ask Mirai bot to remind you of anime in a specific channel, it takes both channel name and anime name as the anime name, [example.](https://imgur.com/a/gJHkQMS)

**Comment by brussell98** [comment]
This repo is for the mirai-bot-core library. Anything relating to Mirai Bot for Discord should be posted on the official [Discord server](https://discord.gg/rkWPSdu).

Also you just type "channel" like the example and help says, not type the name.
